necordjs/necord.org

content/contributing/code-of-conduct.md
content/contributing/commit-convention.md
content/contributing/contribution-guide.md
content/contributing/funding.md
content/getting-started/first-steps.md
content/interactions/context-menus.md
content/interactions/slash-commands.md
content/intro.md
content/overview.md
content/techniques.md
package.json
yarn.lock

feat: Add prettier

---

content/techniques.md

The examples aren't great as sharding a bot application does take some tweaking depending on how you want to implement sharding, however I have covered the basic example using the discord.js `ShardingManager`. Feel free to take a look and correct any mistakes or add more detail, I believe I've added sufficient detail for any novice programmer to successfully implement basic bot sharding with a tip at the end referring to the `discord-cross-hosting` package for sharding across multiple servers. I haven't provided examples using this package as this is beyond the scope of what this package really does.
- Code changes have been tested against the Discord API, or there are no …

Added documentation showing an example of how to achieve sharding.

---

content/interactions/slash-commands.md

This PR **only** includes non-code changes, like changes to documentation, README, **etc.**
Remove unused imports. 

docs(Necord): Update slash-commands

---

content/recipes/pagination.md

Add NecordPaginationModule to imports. Otherwise, example won't work
This PR **only** includes non-code changes, like changes to documentation, README, etc.

docs(pagination): Add NecordPaginationModule to imports

---

content/getting-started.md
content/techniques/validation.md

Fixed a missing Flag key in the intents object and added missing validateCustomDecorators to the validation pipe

Missing elements

---

package.json
yarn.lock

Reverts necordjs/necord.org#206

Revert "chore(deps): bump prism-react-renderer from 1.3.5 to 2.1.0"

---

content/techniques/client-providers.md

Add docs for https://github.com/necordjs/necord/pull/1117

feat: update client providers

---

package.json
yarn.lock

Reverts necordjs/necord.org#256

Revert "chore(deps): bump @docusaurus/remark-plugin-npm2yarn from 2.4.3 to 3.2.0"

---

content/recipes/localization.md

Add docs for [necordjs/localization](https://github.com/necordjs/localization)

feat: add Localization recipe page

---

package.json
yarn.lock

Reverts necordjs/necord.org#262

Revert "chore(deps): bump @docusaurus/remark-plugin-npm2yarn from 2.4.3 to 3.2.1"

---

content/recipes/localization.md

Update docs for https://github.com/necordjs/localization/pull/11

docs(localization): add nested adapter

---

package.json
yarn.lock

Reverts necordjs/necord.org#274

Revert "chore(deps): bump @docusaurus/remark-plugin-npm2yarn from 2.4.3 to 3.3.2"

---

content/recipes/pagination.md

Update Pagination documentation
Module PR: https://github.com/necordjs/pagination/pull/305

docs: update pagination

---

content/contributing/contribution-guide.md
content/getting-started.md
content/intro.md

Update NodeJS version to 18.0.0

chore: update node version

---

content/recipes/lavalink.md

Add Docs for https://github.com/necordjs/lavalink/pull/5

docs(recipes): add lavalink

---

content/getting-started.md
content/interactions/context-menus.md
content/interactions/message-components.md
content/interactions/modals.md
content/interactions/slash-commands.md
content/recipes/lavalink.md
content/recipes/localization.md
content/recipes/pagination.md
content/techniques/async-configuration.md

feat: add examples links for https://github.com/necordjs/examples
fix: add some missing `export`s

docs(*): add examples links and some fixes

---

content/recipes/lavalink.md

Update Docs for https://github.com/necordjs/lavalink/pull/20

docs: update lavalink recipe

---

content/recipes/lavalink.md

Update Listeners example
Update `LavalinkManager` events list
- Lib PR: https://github.com/necordjs/lavalink/pull/26

feat: update

---

content/interactions/message-components.mdx

Add missing anchor in channel select

fix(interactions/message-components): add missing anchor in channel select

---

content/recipes/lavalink.mdx

docs: rename 'PlayerManager' class import to 'PlayerManagerService'
